### ISSUE TITLE
package name on install

### ISSUE THREAD

**Issue by maxprocess** [mrvautin/adminMongo#103]
Hi,

Tried to install but seems to have a dependency reference to adminMongo itself. Thanks.

> npm i admin-mongo
> npm ERR! Windows_NT 10.0.10586
> npm ERR! node v6.4.0
> npm ERR! npm  v3.10.6
> npm ERR! code ENOSELF
> npm ERR! Refusing to install admin-mongo as a dependency of itself

**Comment by mrvautin** [comment]
Could be due to the directory you are installing to being the same name.

See: https://github.com/npm/npm/issues/10387

**Comment by maxprocess** [comment]
i changed it without success :/

`W:\mongodb\gui\admongo>npm i admin-mongo
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "W:\\nodejs\\node.exe" "C:\\Users\\max\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "admin-mongo"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.6
npm ERR! code ENOSELF

npm ERR! Refusing to install admin-mongo as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     W:\mongodb\gui\admongo\npm-debug.log`

i also tried the electron way 

`W:\mongodb\gui\admongo>npm run-script packageWin32

> admin-mongo@0.0.19 packageWin32 W:\mongodb\gui\admongo
> electron-packager ./ adminMongo --out=releases/ --platform=win32 --arch=ia32 --prune --overwrite --ignore=releases/* --icon=public/logo.ico

'electron-packager' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "W:\\nodejs\\node.exe" "C:\\Users\\max\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "packageWin32"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! admin-mongo@0.0.19 packageWin32: `electron-packager ./ adminMongo --out=releases/ --platform=win32 --arch=ia32 --prune --overwrite --ignore=releases/* --icon=public/logo.ico`
npm ERR! Exit status 1`

**Comment by mrvautin** [comment]
Hmm. That is weird. I will have to look into if further.

You won't be able to run as Electron until you have successfully ran the install.

**Comment by TemaSM** [comment]
Maybe you have admin-mongo installed globally, so try this out:
`npm un admin-mongo -g`
`npm cache clean`
Then try to install admin-mongo again by `npm i admin-mongo`
