### ISSUE TITLE
Ideas for new features

### ISSUE THREAD

**Issue by CodersBrothers** [mrvautin/adminMongo#104]
I love this tool, but allways I have the same "problems". Here my ideas for improve the usability:
- Export a complete database
- Import a complete database
- Import a collection
- Remove multiple documents at same time
- Dropdown for select pagination size
- Option, in pagination bar, to go to the last/fists pages. 
- Show MongoDB server version

**Comment by mrvautin** [comment]
Some really good ideas! I will definitely incorporate some or all in future updates. Thanks for contributing.

**Comment by parulsethi** [comment]
Can partial search also be supported. Ex. retrieving all the documents containing certain word entered as query.

**Comment by mrvautin** [comment]
If I understand you correctly, this is currently possible using the "query documents" button. You can query documents using shell syntax.

**Comment by viramaham** [comment]
hi 
I love this  tool
how backup and restore my database?
