### ISSUE TITLE
Copy/Paste in Text Fields (electron)

### ISSUE THREAD

**Issue by nVitius** [mrvautin/adminMongo#105]
Running on OSX, using the electron app built off master you are unable to copy/paste into any of the text fields on the connections page.

**Comment by pbassut** [comment]
I downloaded the binary package on the README and this still doesn't work.

**Comment by mrvautin** [comment]
You will likely have to build it manually using `$ npm run-script packageOsx`

My internet connection doesn't allow me to repackage and upload each code change into the binary downloads.

**Comment by nVitius** [comment]
@mrvautin we could probably set up travis builds to automatically build and deploy to npm. what do you think?

**Comment by mrvautin** [comment]
Sounds good but I'm was not aware you can deploy binaries to NPM. Is this a new thing @nVitius?

**Comment by nVitius** [comment]
I was thinking more along the lines of this:
https://help.github.com/articles/about-releases/
https://docs.travis-ci.com/user/deployment/releases/
