### ISSUE TITLE
Error getting data from Query API

### ISSUE THREAD

**Issue by anned20** [mrvautin/adminMongo#107]
When selecting a collection this error pops up. Everything else is fully working like monitoring getting collections, getting collection counts. But not the documents itself.

**Comment by mrvautin** [comment]
Can you give more info? The console output?

**Comment by anned20** [comment]
No errors at all, just some GET requests

**Comment by anned20** [comment]
Strange, it only happens in Chrome, no errors using Firefox. I'm on Ubuntu 16.04.

**Comment by anned20** [comment]
Found the error. Maybe you could update the Readme. It was AdBlockPlus. If I disable it, it works.
