### ISSUE TITLE
Image on Docker Hub

### ISSUE THREAD

**Issue by nuest** [mrvautin/adminMongo#110]
Hi @mrvautin !

Great app - have you considered publishing the Docker image on Docker Hub? Currently there is only [an image with an outdated version](https://hub.docker.com/r/adicom/admin-mongo/), it would be ideal if you could create an automated build that is based on this repository directly.

I'd gladly help if you think assistance is required.

**Comment by mrvautin** [comment]
Thanks for raising this issue. Automated builds are now setup here: https://hub.docker.com/r/mrvautin/adminmongo/
