### ISSUE TITLE
Mongo basics

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/adminMongo#111]
Ok so I am really new to MongoDB, I have it installed and running.
Can I connect this now to adminMongo or do I need to create usernames etc first?

MongoDB has me completely confused for a Monday morning :(

**Comment by mrvautin** [comment]
Here is some reading for a connection string in MongoDB: https://docs.mongodb.com/manual/reference/connection-string/

A general local install with no authentication can be connected like so:

![image](https://cloud.githubusercontent.com/assets/299398/18629481/d22c61bc-7ea4-11e6-817e-5d00653229a2.png)

**Note: this is the default port**

**Comment by thedaftbadger** [comment]
Ok so if I need to edit the string it would be a local account not a mongodb account for the connection

**Comment by mrvautin** [comment]
When referring to "account", I'm assuming your mean user accounts. This is probably one of the worst things about managing MongoDB in my opinion.

If you want authentication (assume you do) you need to create a user through the MongoDB shell like this: http://tecadmin.net/create-drop-users-in-mongodb/ 

Official docs are here: https://docs.mongodb.com/manual/reference/method/db.createUser/

**Comment by thedaftbadger** [comment]
All sorted. I agree it's note the best!
For testing the password protection built into AdminMongo will be ok :)
