### ISSUE TITLE
pre compiled app osx not working

### ISSUE THREAD

**Issue by jvega** [mrvautin/adminMongo#113]
don't show any window

version: v1.2.6
osx: captain

logs
9/19/16 17:43:38.975 adminMongo Helper[8146]: GVA info: preferred scaler idx 0

**Comment by mrvautin** [comment]
Does it work when building manually?

The pre compiled are a little out of date as uploading files that large on my internet connection is very painful.

**Comment by jvega** [comment]
it doesn't work

**Comment by mrvautin** [comment]
Its working for me on latest osx. Are you able to give more information? Googling this error and it seems stacks of Electron apps have the same issue for various reasons.

**Comment by jvega** [comment]
osx: 10.11.6 (el capitan)
node: 6.3.1 (nvm)

steps that I used
```
npm i admin-mongo 
npm install electron-packager
npm install electron-prebuilt
npm run-script packageOsx
```
I open the compiled app from `releases` directory and nothing happens, just the icon in the dock, nothing more

what steps are you using to compile?

**Comment by mrvautin** [comment]
I'm using the same steps.

Node: 6.6.0
Osx: 10.11.6
Electron: 1.4.0 (updated from package.json version to test)

Compiles fine and runs fine. Not sure how but I will have to look into it further.
