### ISSUE TITLE
NPM Install moved repo contents

### ISSUE THREAD

**Issue by mcclowes** [mrvautin/adminMongo#116]
After git pull-ing to bring the repo up to date, I then npm install-ed.

All the contents of the adminMongo repo were all moved to my user root dir.

Any idea why?

**Comment by mrvautin** [comment]
This might have been caused by the post-install script. The idea behind it is to copy the code up one directory level if installed purely by NPM. On a git-pull/clone it shouldnt do anything.

**Comment by gyratorycircus** [comment]
I encountered the same problem. Regardless of which directory installed to via npm, all admin-mongo files are saved to user root.

**Comment by mrvautin** [comment]
What OS are you running this on @gyratorycircus & @mcclowes? Could be a path issue.

**Comment by mcclowes** [comment]
macOS Sierra, fully up to date

Maxi Clayton Clowes

maxcc@me.com(mailto:maxcc@me.com)  
07976 136 097(tel:07976%20136%20097)

**Comment by gyratorycircus** [comment]
macOS Sierra as well. I had a coworker on OS X 10.11 attempt and everything installed as expected.

**Comment by smmoosavi** [comment]
same problem

Ubuntu 14.04 LTS
npm 3.10.3
v6.6.0

**Comment by smmoosavi** [comment]
copy all and post install script is bad Idea

please see this doc:
https://docs.npmjs.com/files/package.json#bin
