### ISSUE TITLE
Handling symbols in the Edit page

### ISSUE THREAD

**Issue by YasharF** [mrvautin/adminMongo#118]
When editing an existing document that is in the DB, if there is a string field with a value that includes certain characters such as colon( : ) somewhere in the string , the save function fails with error "Syntax error. Please check the syntax".

**Comment by mrvautin** [comment]
Are you sure? I have can edit a document, add colon ( : ) to a string and save without issue. Could there be a syntax error somewhere else?

**Comment by YasharF** [comment]
I dug in more, it is a combination of colon ( : ) and comma ( , )

**Fails to Save with a Syntax Error - comma and colon:**
```
{
    "_id": ObjectId("5806fa250a0c6e03799c5ceb"),
    "updatedAt": ISODate("2016-10-19T04:44:21.060Z"),
    "createdAt": ISODate("2016-10-19T04:44:21.060Z"),
    "description": "abcd, abc : abcd",
    "__v": 0
}

```

**Saves OK - colon, no comma:**
```
{
    "_id": ObjectId("5806fa250a0c6e03799c5ceb"),
    "updatedAt": ISODate("2016-10-19T04:44:21.060Z"),
    "createdAt": ISODate("2016-10-19T04:44:21.060Z"),
    "description": "abcd abc : abcd",
    "__v": 0
}

```

**Saves OK - comma, no colon :**
```
{
    "_id": ObjectId("5806fa250a0c6e03799c5ceb"),
    "updatedAt": ISODate("2016-10-19T04:44:21.060Z"),
    "createdAt": ISODate("2016-10-19T04:44:21.060Z"),
    "description": "abcd, abc  abcd",
    "__v": 0
}

```

**Comment by YasharF** [comment]
Thank you for the quick fix
