### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by khailevn** [mrvautin/adminMongo#12]
When I start the web server using the command:

> npm start

I got a list of errors:

> npm ERR! admin-mongo@0.0.1 start: `node app.js`
> npm ERR! Exit status 127
> npm ERR! 
> npm ERR! Failed at the admin-mongo@0.0.1 start script.
> npm ERR! This is most likely a problem with the admin-mongo package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node app.js
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls admin-mongo
> npm ERR! There is likely additional logging output above.
> npm ERR! System Linux 4.2.0-25-generic
> npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
> npm ERR! cwd /opt/adminMongo
> npm ERR! node -v v0.10.25
> npm ERR! npm -v 1.4.21
> npm ERR! code ELIFECYCLE
> npm WARN This failure might be due to the use of legacy binary "node"
> npm WARN For further explanations, please read
> /usr/share/doc/nodejs/README.Debian
>  
> npm ERR! 
> npm ERR! Additional logging details can be found in:
> npm ERR!     /opt/adminMongo/npm-debug.log
> npm ERR! not ok code 0
Currently, my environment is Ubuntu 15.10. Anyone can help me fix that?

**Comment by mrvautin** [comment]
This is normally a node issue. Please try the recommendations here: http://stackoverflow.com/questions/21168141/cannot-install-packages-using-node-package-manager-in-ubuntu
