### ISSUE TITLE
Impossible to find a document with its _id

### ISSUE THREAD

**Issue by VincentPeraud** [mrvautin/adminMongo#125]
Hi,

It's impossible to get a document with its _id, what the fuck man, am I doing it the wrong way?

![image](https://cloud.githubusercontent.com/assets/1888602/20968417/ca617210-bc84-11e6-86ec-bd65719932e0.png)

![image](https://cloud.githubusercontent.com/assets/1888602/20968443/dd0b1e34-bc84-11e6-8834-6737cde24ad3.png)

-> "No document found"

Thanks,
V.

**Comment by mrvautin** [comment]
That will be looking for a string document ID but yours is an ObjectID.

You need to use the `Query documents` button with this:

```
{ 
  "_id": ObjectId("your_objectid")
}
```

**Comment by RrOoSsSsOo** [comment]
I've created the #196 to fix this aspect! (Many many important for me!!)
