### ISSUE TITLE
I cant use the command npm install in any project because of the admin-mongo npm

### ISSUE THREAD

**Issue by Ugur22** [mrvautin/adminMongo#127]
I'm getting the folllowing error:

 Failed at the admin-mongo@0.0.20 postinstall script 'node ./lib/npm_postinstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the admin-mongo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./lib/npm_postinstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs admin-mongo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls admin-mongo
npm ERR! There is likely additional logging output above.

**Comment by mrvautin** [comment]
The `adminMongo` postinstall script was removed due these issues. I would suggest updating `adminMongo` to the latest version from Git.

**Comment by Ugur22** [comment]
I tried to update it with npm update admin-mongo but it didn't work.

**Comment by mrvautin** [comment]
Not sure those changes are in npm, this is why I suggested to update from Git.

**Comment by Ugur22** [comment]
how do I update it through git ?

**Comment by mrvautin** [comment]
`git pull origin master`
