### ISSUE TITLE
Electron

### ISSUE THREAD

**Issue by kiralikbeyin** [mrvautin/adminMongo#128]
udo npm run-script packageLinux

> admin-mongo@0.0.20 packageLinux /var/opt/adminMongo
> electron-packager ./ adminMongo --out=releases/ --platform=linux --arch=ia32 --prune --overwrite --ignore=releases/* --icon=public/logo.ico

sh: 1: electron-packager: not found

npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run-script" "packageLinux"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! admin-mongo@0.0.20 packageLinux: `electron-packager ./ adminMongo --out=releases/ --platform=linux --arch=ia32 --prune --overwrite --ignore=releases/* --icon=public/logo.ico`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the admin-mongo@0.0.20 packageLinux script 'electron-packager ./ adminMongo --out=releases/ --platform=linux --arch=ia32 --prune --overwrite --ignore=releases/* --icon=public/logo.ico'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the admin-mongo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-packager ./ adminMongo --out=releases/ --platform=linux --arch=ia32 --prune --overwrite --ignore=releases/* --icon=public/logo.ico
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs admin-mongo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls admin-mongo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/opt/adminMongo/npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run-script',
1 verbose cli   'packageLinux' ]
2 info using npm@3.10.10
3 info using node@v7.2.1
4 verbose run-script [ 'prepackageLinux', 'packageLinux', 'postpackageLinux' ]
5 info lifecycle admin-mongo@0.0.20~prepackageLinux: admin-mongo@0.0.20
6 silly lifecycle admin-mongo@0.0.20~prepackageLinux: no script for prepackageLinux, continuing
7 info lifecycle admin-mongo@0.0.20~packageLinux: admin-mongo@0.0.20
8 verbose lifecycle admin-mongo@0.0.20~packageLinux: unsafe-perm in lifecycle true
9 verbose lifecycle admin-mongo@0.0.20~packageLinux: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/var/opt/adminMongo/node_modules/.bin:/usr$
10 verbose lifecycle admin-mongo@0.0.20~packageLinux: CWD: /var/opt/adminMongo
11 silly lifecycle admin-mongo@0.0.20~packageLinux: Args: [ '-c',
11 silly lifecycle   'electron-packager ./ adminMongo --out=releases/ --platform=linux --arch=ia32 --prune --overwrite --ignore=releases/* --icon=publ$
12 info lifecycle admin-mongo@0.0.20~packageLinux: Failed to exec packageLinux script
13 verbose stack Error: admin-mongo@0.0.20 packageLinux: `electron-packager ./ adminMongo --out=releases/ --platform=linux --arch=ia32 --prune --overw$
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:33:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:885:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid admin-mongo@0.0.20
15 verbose cwd /var/opt/adminMongo
16 error Linux 4.4.0-53-generic
17 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run-script" "packageLinux"
18 error node v7.2.1
19 error npm  v3.10.10
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error admin-mongo@0.0.20 packageLinux: `electron-packager ./ adminMongo --out=releases/ --platform=linux --arch=ia32 --prune --overwrite --ignore=r$
24 error spawn ENOENT
25 error Failed at the admin-mongo@0.0.20 packageLinux script 'electron-packager ./ adminMongo --out=releases/ --platform=linux --arch=ia32 --prune --$
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the admin-mongo package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     electron-packager ./ adminMongo --out=releases/ --platform=linux --arch=ia32 --prune --overwrite --ignore=releases/* --icon=public/logo.i$
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs admin-mongo
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls admin-mongo
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]

**Comment by mrvautin** [comment]
Try installing `electron-packager` globally with `npm -i electron-packager -g`

**Comment by kiralikbeyin** [comment]
Thank you!
Now i am running it on digital ocean.
