### ISSUE TITLE
Standard user not documented

### ISSUE THREAD

**Issue by JanKoppe** [mrvautin/adminMongo#13]
I tried to setup adminMongo as per instructions. When I opened the URL, I was asked for a user and password, which was not documented anywhere (obvious). From the source code, I could read that it was user: `test`, password: `password`. You might want to document that somewhere. If you want, I can make a PR to add it to the Readme.MD

**Comment by mrvautin** [comment]
Thanks for picking this up, some code was added by mistake. Remove in 8f27dd3911be309ef4cd312ff439ed95d755fd32.
