### ISSUE TITLE
Cant able to run the software

### ISSUE THREAD

**Issue by softnic** [mrvautin/adminMongo#132]
first i install the node then

run the cmd: mkdir adminMongo && cd adminMongo && npm i admin-mongo && npm start

Failed to run the npm start 

Because it created the extra folders  "node_modules/admin-mongo" so my path is /admin-mongo/node_modules/admin-mongo then after running the cmd it show in multiple files that =>  "invalid token > " error

and in connection page i enter username and password for mongodb its didn't accept the url (may be it also need the auth database name which was missing) and when i removed the user and password it accept the url and further cant able to run the software

**Comment by mrvautin** [comment]
See updated install instructions due to many issues installing directly from NPM: https://github.com/mrvautin/adminMongo/blob/master/README.md
