### ISSUE TITLE
Proper Installation Directory

### ISSUE THREAD

**Issue by DRichter4764** [mrvautin/adminMongo#135]
I am trying to install adminMongo on a Centos 7 server. I have been able to successfully start adminMongo, showing it is running on http://mydomain.com:4321 but I am running it from my home directory and am unable to access the website address.

Does adminMongo need to be installed within my /var/www/html directory to work properly or am I missing a step in the installation?

**Comment by mrvautin** [comment]
We don't recommend running on a public server and I would highly recommend securing this heavily. 

You will have to serve `adminMongo` using some kind of web server. Eg: Nginx or Apache.

**Comment by DRichter4764** [comment]
I ended up installing on a local machine and will connect to my Mongo instance via a remote connection. Thanks for your help!
