### ISSUE TITLE
Missing packages

### ISSUE THREAD

**Issue by realflash** [mrvautin/adminMongo#138]
I did an `npm install` but it didn't install the packages needed. I had to add these manually:

- promise
- handlebars
- object-assign

Missing from packages.json?

**Comment by mrvautin** [comment]
No these are not direct dependencies of `adminMongo`. This could be related to your other issue #137. What version of Nodejs are you running?

**Comment by realflash** [comment]
Stable (packaged) version for Ubuntu 14.04 LTS, 0.10.25. I realise this is probably old, but the OS will be supported until April 2019. If adminMongo needs a later version of Node.js, could there be a mention of that in the README.md? Thanks.

**Comment by mrvautin** [comment]
See #137.
