### ISSUE TITLE
can't name index correctly

### ISSUE THREAD

**Issue by matze1234** [mrvautin/adminMongo#139]
Hello,
i'm trying to set an index for a property named 'title'.
It doesn't work without quotes, e.g.:
{title: 1} 
Nor does it work with single quotes. 
But if i use double quotes like 
{"title": 1}
the result key is this:
{"\"{\\\"title\\\":1}\"":1}

Could you please give me an example for what i should write into the curly brackets to achieve this result:
Name:     Key:
title_1      {title": 1}

Thanks.

**Comment by matze1234** [comment]
It works fine after i replace JSON.stringify by JSON.parse in 
routes\collection.js
line 155

**Comment by mrvautin** [comment]
Are you able to submit a PR with your fixes?

**Comment by mrvautin** [comment]
Refer PR #140
