### ISSUE TITLE
nedb dependency

### ISSUE THREAD

**Issue by Jule-** [mrvautin/adminMongo#143]
`nedb` seems to not being designed for huge DB. After some months of run the stat database become huge, about ~800Mo, and   `nedb` make adminMongo crashing at start.

**Comment by mrvautin** [comment]
`nedb` is just used for the monitoring. If you have a large DB or having problems with it, you can simply turn it off.

**Comment by Jule-** [comment]
So #142 is linked to `nedb` right?

How can I turn it off?

Thanks.

**Comment by mrvautin** [comment]
It's related. You can turn off using the config file here: https://github.com/mrvautin/adminMongo#configuration
