### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by 578575** [mrvautin/adminMongo#144]
mac:
Uncaught Exception:
Error: EROFS: read-only file system, open '/private/var/folders/x5/tcy94vvn0038f2r3xw_kwfw80000gn/T/AppTranslocation/88045CBF-2F61-4F03-B004-A5625E657DED/d/adminMongo.app/Contents/Resources/app/data/dbStats.db'
    at Error (native)

**Comment by mrvautin** [comment]
This is likely a permissions issue. Are you manually packaing the app from source or using the downloadable binaries?

**Comment by deckvig** [comment]
@mrvautin same issuse use binaries.
![image](https://cloud.githubusercontent.com/assets/15033627/23824909/b6466904-06ba-11e7-96ed-8f90dcd3f078.png)

**Comment by mhjb** [comment]
me too

**Comment by leoschweizer** [comment]
This still happens with the prebuilt binary on MacOS 10.13. Not sure why this issue is closed?

**Comment by alexchen1875** [comment]
me too  on MacOS 10.13.4
![image](https://user-images.githubusercontent.com/3668637/49558916-c2250380-f947-11e8-98b9-384550e6de1f.png)
