### ISSUE TITLE
MongoDB Cloud Atlas

### ISSUE THREAD

**Issue by PaulieScanlon** [mrvautin/adminMongo#148]
Hi, i've set up a 'cluster' on MongoDB Atlas and it gives me a connection string which all works in my Node app but after i connect Admin Mongo it crashes. 

Errors look like this:
process.nextTick(function() { throw err; });

...and this
TypeError: Cannot read property 'returned' of undefined

Any ideas?

**Comment by mrvautin** [comment]
Are you setting the approproate `replSet` options at the connection screen?

Unfortunately I don't have a replica set I can test with.
