### ISSUE TITLE
Error - missing delimiting slash between hosts and options

### ISSUE THREAD

**Issue by chrisbull** [mrvautin/adminMongo#15]
Getting this error `Error - missing delimiting slash between hosts and options` when connecting to `mongodb://127.0.0.1: 27017`. 

Help?

**Comment by mrvautin** [comment]
Looks like you have an extra space between the ":" and the port. Eg: Should be: `mongodb://127.0.0.1:27017`

**Comment by chrisbull** [comment]
@mrvautin Wow. Should have seen that. Thanks!
