### ISSUE TITLE
Backups and Restore db problem

### ISSUE THREAD

**Issue by dmitrydrynov** [mrvautin/adminMongo#151]
Error - Cannot read property 'connString' of undefined
routes/database.js

**Comment by Myshkouski** [comment]
You could try to replace routes/database.js:119
`var uri = connection_list['Local'].connString;`
with
`var uri = connection_list[req.params.conn].connString;`

**Comment by niyazialpay** [comment]
I'm gettig error when i press backup button. 

Backup DB error: MongoError: connection 6 to 127.0.0.1:27017 closed
