### ISSUE TITLE
Issue with Dockerfile, environmental variables and config

### ISSUE THREAD

**Issue by ianfinch** [mrvautin/adminMongo#152]
**Issue**

- The Dockerfile copies across everything in the repo into the docker image.
- This includes the empty config/app.json file
- The application only uses configuration via ENV variables if config/app.json does not exist
- This means that ENV variables are ignored when running the Docker image

**Quick fix**

Add a line to the Dockerfile to remove config/app.json.

I have done this by creating a new Dockerfile based on the existing Docker image ...

FROM mrvautin/adminmongo
RUN rm /app/user/config/app.json
CMD node app.js

For a fix in this repo, the "RUN" line could be added to the repo's Dockerfile.

**Comment by mrvautin** [comment]
Happy for you to submit a PR with your fixes. I have an extremely limited knowledge of Docker and it's setup/commands.

**Comment by ianfinch** [comment]
Closed following PR.
