### ISSUE TITLE
docsPerPage event not have $('#app_context').val()

### ISSUE THREAD

**Issue by dbit-xia** [mrvautin/adminMongo#154]
// when docs per page is changed
    $(document).on('change', '#docsPerPage', function(){
        localStorage.setItem('docsPerPage', $('#docsPerPage').val());
        window.location = **# $('#app_context').val() +** '/app/' + $('#conn_name').val() + '/' + $('#db_name').val() + '/' + $('#coll_name').val() + '/view/1';
    });

**Comment by mrvautin** [comment]
👍
