### ISSUE TITLE
Problem with expanding large documents in mobile browsers

### ISSUE THREAD

**Issue by aminmazi** [mrvautin/adminMongo#157]
Hi, thanks for such a good project,
When I log in to adminMongo with my mobile browser (Google chrome Android, version 57, running on Motorola Nexus 6 with Android 7.1) , for Larg documents,  neither the scroll bar moves with touch nor the expand button works.
I think It also would be useful if the portal had an expand all button for documents in current page.

**Comment by mrvautin** [comment]
To be perfectly honest, I've hardly tested `adminMongo` on mobile browsers. It's purpose is not really aimed at mobile browsers due to it being an app aimed at developers.

With that said, if you can make it work nice on mobile I will approve a PR.
