### ISSUE TITLE
Error with pre-built version

### ISSUE THREAD

**Issue by MrTreasure** [mrvautin/adminMongo#159]
My os is Win10 64bit, and I try to use the pre-built version but it just give me a white screen. Nothing happen. Even I use administrtar permission. Still like that. Then I try 32bit version. Same error. 
I could use node version.

**Comment by apat183** [comment]
Same here win 64bit, I even built it manually using ```npm run-script packageWin32``` but still getting white screen. Using local node server is running fine though.

I tried to show dev tools to see error but nothing works to open dev tools, added https://www.npmjs.com/package/electron-debug package and built again but still not opening dev tools.

**Comment by mrvautin** [comment]
Unfortunately I don't have a Windows machine to help resolve this one. If you buy me one, I will fix it ;)

**Comment by MrTreasure** [comment]
Thanks for your reply. U said ```The Electron builds have been tested on Mac and Windows 10``` Maybe we use different version. Now I use Robomongo. Anyway, thanks for writing this wonderful software.

**Comment by leolux** [comment]
I have the same issue with Windows 10. There is only a white screen visible.
@mrvautin why did you close this issue? How do solve this issue?

**Comment by mrvautin** [comment]
@leolux because the issue is 4 months old with no input from anyone and I cannot reproduce due to not having access to a Windows machine.
