### ISSUE TITLE
Demo Page is an Ad

### ISSUE THREAD

**Issue by keithweaver** [mrvautin/adminMongo#172]
When I click demo, it takes me to an ad. Use Github pages and you won't need to pay for hosting your demo.

https://www.youtube.com/watch?v=LP4OQvLCWKY

**Comment by keithweaver** [comment]
Fixed.

**Comment by cognitom** [comment]
Still it navigates to an unexpected page, doesn't it?
Looks that the domain was expired.
http://demo.adminmongo.com/
