### ISSUE TITLE
How to search for date?

### ISSUE THREAD

**Issue by JonFranchi** [mrvautin/adminMongo#188]
I have data like this:

`"created_at": "2017-12-02T04:25:35.297Z"
`

How can I search for a date greater than that?  I've tried variates with $gte, $gt, ISOdate(), etc.  everything that appears otherwise valid returns an invalid JSON error at the first character of the nested brackets necessary for a search like that.

**Comment by ruisebastiao** [comment]
for me this works:
```
 "created_at":{
        "$gte": ISODate("2017-12-02T04:25:35.297Z")   
    }
```
did you forget the quotation marks ("$gte")?
