### ISSUE TITLE
JSON Schema Validation

### ISSUE THREAD

**Issue by rajeevkumarsharma** [mrvautin/adminMongo#20]

**Comment by mrvautin** [comment]
When editing existing and inserting new documents, the editor currently has (should have) JSON validation. 

Please advise if this is not working for you.

**Comment by rajeevkumarsharma** [comment]
It is supported when we added new document, but importing and validation that json is missing

**Comment by mrvautin** [comment]
What "importing" are you referring to?

**Comment by mrvautin** [comment]
Refer c3f8e79fee650565ceb0babb25f67c89cd5f7ce7.
