### ISSUE TITLE
Auto connect to db if db config provided

### ISSUE THREAD

**Issue by rajeevkumarsharma** [mrvautin/adminMongo#21]

**Comment by mrvautin** [comment]
This could be OK. I assume you mean that when hitting the "/" and only one config is setup it should auto connect and redirect?

**Comment by rajeevkumarsharma** [comment]
Hi,
Lets say i have local as well as mongolab.
I provide mongodb uri for both in config file, when i start server than i should check in config uri and connect me with these databases (if not connected already). Also i am able to connect to db manually.

**Comment by mrvautin** [comment]
Doesn't the app already do this?

**Comment by rajeevkumarsharma** [comment]
For first time it require connection string.
If i specify connection strings in config than it should auto connect to that db.

**Comment by rajeevkumarsharma** [comment]
Once connecting it works fine
