### ISSUE TITLE
Add mongodb query support

### ISSUE THREAD

**Issue by rajeevkumarsharma** [mrvautin/adminMongo#22]

**Comment by drakoumel** [comment]
It would be a good feature yes.

**Comment by samrm111** [comment]
:+1:

**Comment by coolbung** [comment]
:+1:

**Comment by mrvautin** [comment]
Added functionality to run extended JSON formatted queries. There were a few changes to the API which have been done to support this and the "simple" search feature was also caught up in the changes.

I've tested as thoroughly as I can but without any proper tests cases (this project doesn't have any yet.. Hint to anyone who wants to help here?) I might have missed something and broken functionality.

Please raise issue or pull request if anything found.
