### ISSUE TITLE
Launching AdminMongo on a virtual machine

### ISSUE THREAD

**Issue by h4rris** [mrvautin/adminMongo#226]
I'm trying to run mongodb and adminMong on a virtual machine using localhost and port 80 as configuration:

`{
    "app": {
        "host": "localhost",
        "port": 80,
        "locale": "en",
        "monitoring": true
    }
}`
And when i open localhost:80 on google chrome it not working, What can I do please?

**Comment by bitmeal** [comment]
you need to be root to bind on port 80
