### ISSUE TITLE
admin_mongo not running with Docker

### ISSUE THREAD

**Issue by ankur20us** [mrvautin/adminMongo#229]
I tried the following command in order to run the admin_mongo in my local machine with Docker and to my surprise the command that used to work for the admin_mongo (with Docker) is not working:

Here is the command:

`docker run -d -p 1234:1234 --name="admin_mongo" mrvautin/adminmongo ` 

This command used to give me a simple UI in the browser on Port 1234 (http://localhost:1234) where I can create a connection to my localhost and start working with it accordingly, but now it is showing this:

![image](https://user-images.githubusercontent.com/1659428/49342584-47c45d00-f683-11e8-83b4-e03fa1ae42d6.png)

**Comment by suchcodemuchwow** [comment]
Have the same issue

**Comment by Waishon** [comment]
Hey there,

we had the same issue. It seems that the mongo-admin isn't listing on 0.0.0.0 by default.
When adding the HOST environment variable everything works fine.
`- HOST=0.0.0.0`

**Comment by ankur20us** [comment]
> Hey there,
> 
> we had the same issue. It seems that the mongo-admin isn't listing on 0.0.0.0 by default.
> When adding the HOST environment variable everything works fine.
> `- HOST=0.0.0.0`

Thanks for this, I got the UI in the browser but when I try to connect to localhost by giving the connection string as:

** mongodb://docker.for.mac.localhost:27017** 

_Since my mongo instance is also on docker and it's a dev machine that's why I am using interacting between the containers via that URI,_ 

I am getting **Slash in host identifier** error. Any idea regarding that, by the way, my mongo is not behind any username and password scheme.

**Comment by RoyLH** [comment]
> I tried the following command in order to run the admin_mongo in my local machine with Docker and to my surprise the command that used to work for the admin_mongo (with Docker) is not working:
> 
> Here is the command:
> 
> `docker run -d -p 1234:1234 --name="admin_mongo" mrvautin/adminmongo `
> 
> This command used to give me a simple UI in the browser on Port 1234 (http://localhost:1234) where I can create a connection to my localhost and start working with it accordingly, but now it is showing this:
> 
> ![image](https://user-images.githubusercontent.com/1659428/49342584-47c45d00-f683-11e8-83b4-e03fa1ae42d6.png)

docker run -d -e HOST=0.0.0.0 -e PASSWORD="xxx"  -e LOCALE="en" -p 1234:1234 -v YOUR_LOCAL_PATH:/app/user/config  --name="adminmongo" mrvautin/adminmongo

**Comment by RoyLH** [comment]
docker run -d -e HOST=0.0.0.0 -e PASSWORD="xxx"  -e LOCALE="en" -p 1234:1234 -v YOUR_LOCAL_PATH:/app/user/config  --name="adminmongo" mrvautin/adminmongo

**Comment by RoyLH** [comment]
-e HOST=0.0.0.0 -e PASSWORD="xxx" -e LOCALE="en" could not write to app.json of the container until you add -v YOUR_LOCAL_PATH:/app/user/config, and then this command will create app.json in YOUR_LOCAL_PATH and write these configurations all above to this file, it works.

**Comment by ghostry** [comment]
I try `docker run -d -p 1234:1234 --name=adminmongo -e HOST=0.0.0.0 mrvautin/adminmongo`.it's can be work .
Why not write the correct commands to the README.md?

**Comment by antwal** [comment]
> I try `docker run -d -p 1234:1234 --name=adminmongo -e HOST=0.0.0.0 mrvautin/adminmongo`.it's can be work .
> Why not write the correct commands to the README.md?

Thanks, now working also with Docker Compose:

```
version: '2'
services:
  mongo-service:
    image: mongo
    ports:
      - 27017:27017
  adminmongo-service:
    image: mrvautin/adminmongo
    restart: "always"
    links: ['mongo-service:mongo']
    environment:
      - CONN_NAME=whatever
      - DB_HOST=mongo
      - DB_PORT=27017
      - HOST=0.0.0.0
    ports:
      - 1234:1234
```

**Comment by ankur20us** [comment]
Closing this as we have a solution:

`docker run -d -p 1234:1234 --name=adminmongo -e HOST=0.0.0.0 mrvautin/adminmongo`

Thanks all.

**Comment by rjain15** [comment]
@ankur20us can you double click and explain why do I have to specify HOST=0.0.0.0 and in the connection string `mongodb://docker.for.mac.localhost:27017`

I am running this in kubernetes/gke and I want to know what would the equivalent. Do I have to give the external IP Address and expose the mongodb service?

**Comment by ankur20us** [comment]
In order to tell the setup from where ever the call comes allow it and respond with proper response rather than denying the connection.

This setting is usually important to restrict the outsider machines to get connection
