### ISSUE TITLE
Typing Korean characters in the Edit page

### ISSUE THREAD

**Issue by byeokim** [mrvautin/adminMongo#233]
There is an issue when typing Korean characters in [embedded Ace editor](https://github.com/mrvautin/adminMongo/blob/edcef9d12f22298e0ef4e509f88f06ea8967647c/views/layouts/layout.hbs#L22). As can be seen below, characters typed were displayed twice.

![image](https://user-images.githubusercontent.com/29354589/51164927-efb78200-18e1-11e9-8038-097d3d73304e.png)

![image](https://user-images.githubusercontent.com/29354589/51164945-f6de9000-18e1-11e9-9ce9-93e7f741e100.png)

![image](https://user-images.githubusercontent.com/29354589/51164958-0362e880-18e2-11e9-94ce-eca8a8658d23.png)

The issue has been fixed in the later versions of [the Ace editor](https://github.com/ajaxorg/ace), but the fixed version is not integrated with this repository. So if you want to solve the above issue, manually replace contents of [ace directory](https://github.com/mrvautin/adminMongo/tree/master/public/js/ace) of your installation with [the latest build](https://github.com/ajaxorg/ace-builds/tree/0d62c26de7b2e1922d8dd95ba587c9845c018c51/src-min) of the Ace editor.

I am not sure if the issue deserves a pull request, so I am posting here.

By the way, thank you @mrvautin for this amazing app!

**Comment by ingridlar** [comment]
Hi!
I cant make the google-map-react-examples/src/examples/MarkerInfoWindow.js to work.
Have I missed something?

![Skärmavbild 2020-05-18 kl  20 56 42](https://user-images.githubusercontent.com/26634605/82249474-1ceac900-994a-11ea-9943-06e49bc2c272.png)

**Comment by byeokim** [comment]
Your question is not about adminMongo. Could you post the issue to [google-map-react-examples](https://github.com/google-map-react/google-map-react-examples) repository or StackOverflow with code?
