### ISSUE TITLE
Suggest that people also check out Mongoku

### ISSUE THREAD

**Issue by julien-c** [mrvautin/adminMongo#237]
Mongoku is a new, modern and maintained Web-based client for Mongo, inspired by adminMongo:
https://github.com/huggingface/Mongoku

It's built on Node.js (using Typescript) and Angular.

![mongoku-demo](https://user-images.githubusercontent.com/326577/55095180-13d7d200-508e-11e9-9c37-3d047f99e3f5.gif)

**Comment by botzill** [comment]
But you don't have users and roles management, right @julien-c ?
