### ISSUE TITLE
Help: How to secure adminMongo

### ISSUE THREAD

**Issue by rjain15** [mrvautin/adminMongo#240]
I am running this with in a public cloud and I want to secure the access to adminMongo. I have added password env variables (kuberentes deployment) and it seems I can still access it without any password. Where is the password used? what is the user name? Is there a login page? The documents are not clear on how the env variable password gets used. Thanks!

**Comment by MauroEldritch** [comment]
In my case the `PASSWORD` env variable isn't taken into account, but HOST and PORT are (I'm using Rancher by the way). I found a nice workaround by modifying the `app.json` file inside the `config` directory (you may want to add this as a volume to make it persistent):

```bash
root@mysite:/var/lib/docker/volumes/my_vol/_data# cat app.json 
{
    "app": {
        "password": "my_nice_password"
    }
}

```

Hope it helps. Have a nice day!
