### ISSUE TITLE
Replace cdn with local instances

### ISSUE THREAD

**Issue by TrySpace** [mrvautin/adminMongo#27]
I pulled the repo, and am on a very slow mobile connection at the moment. And pulling the different cdn sources like `https://maxcdn.bootstrapcdn.com/bootswatch/3.3.6/flatly/bootstrap.min.css` is really slow or just times out after a while. And it will block everything else, so I'm waiting 60 seconds for a new page to load each time.

When I remove the line:

        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.6/flatly/bootstrap.min.css">

It loads at a normal speed, and it doesn't look like it is being used anyways, and even seems to be duplicate/redundant because this is also there (`coll-layout.hbs`):

     <link rel='stylesheet' href='/bootstrap/css/bootstrap.min.css' />

I think it would be better for the project to include these locally, instead of relying on external sources.

Also so that it will still work completely offline, or in an isolated network.

**Comment by TrySpace** [comment]
Also `laout.hbs` has the same issue

**Comment by TrySpace** [comment]
Made pull requests: #28 and #29

**Comment by mrvautin** [comment]
That file is a bootstrap theme and is used to compliment bootstrap.css. If you add the file localled in the pull request I can approve it.

**Comment by mrvautin** [comment]
Without the file, everything will render fine just not the expected style changes with the theme. 

It does seem silly to server from a CDN though as all people won't use adminMongo (hopefully) on a public facing server to get the benefits of serving from a CDN.
