### ISSUE TITLE
Couldn't I access the host from remote?

### ISSUE THREAD

**Issue by Kylinlin** [mrvautin/adminMongo#3]
I recognized that I can't access the host from other machine after I install the project on my centos7. But as you known, The host of linux usually only work in text mode, so I will be very appreciate if I can access the host from remote host, just like tomcat.

**Comment by mrvautin** [comment]
I'm not really sure what you mean. Are you able to explain it differently?

adminMongo is generally only installed on local machines to access local or remote development databases. I wouldn't recommend installing adminMongo on a public facing remote server.

**Comment by mrisinger** [comment]
1. Make sure your CentOS 7 firewall is open:
sudo systemctl <stop/disable> firewalld
2. Edit adminMongo/app.js and and change the host to 0.0.0.0:
var app_host = '0.0.0.0';

That will do the trick.

**Comment by mrvautin** [comment]
If you are using the latest version you could change step 2 and edit the /config/app.json like so:

```
{
    "app": {
        "host": "0.0.0.0",
        "port": 1234
    }
}
```

**Comment by Kylinlin** [comment]
It works, thank you very much, you are so kind.

**Comment by mrvautin** [comment]
Good stuff.
