### ISSUE TITLE
Editing an entry doesn't support objects such as ISODate

### ISSUE THREAD

**Issue by samrm111** [mrvautin/adminMongo#31]
When I try to edit an entry and add an ISODate() object, it gives me a syntax error :
`Unexpected 'I'`
Same for ObjectId.

**Comment by mrvautin** [comment]
At this stage you will need to write your documents in [Mongodb extened json](https://docs.mongodb.org/manual/reference/mongodb-extended-json/) unless someone has a better solution long term.

**Comment by samrm111** [comment]
If you want I can take this issue. I will make a check in front end for all supported operators by mongo.

**Comment by mrvautin** [comment]
Sure! More than happy if people want to help.

**Comment by mrvautin** [comment]
Can now edit and insert BSON formatted documents. Had to compromise a little on the Ace live syntax checking/highlighting for now (will have to work out a BSON syntax checker in Ace at some point). 

The BSON formatted document is converted to extended JSON and POST to the route which is then parsed back to BSON to be updated/inserted. At this stage the syntax checking is done on the server side. Not ideal in the long term as you dont know where the syntax error actually is.

Documents such as this have been tested successfully:

```
{
    "_id": ObjectId("56d3833a336113d805fed950"),
    "another_id": ObjectId("56d3833a336113d805fed950"),
    "item": "MyIRAFVEd2aImaq7zN3u/w==12",
    "dte_test": ISODate("2016-02-28T23:34:12.391Z"),
    "timestamp": Timestamp(1456984782, 1),
    "new_dte": new Date()
}
```
