### ISSUE TITLE
Failed DB update reports success

### ISSUE THREAD

**Issue by MaitreyaBuddha** [mrvautin/adminMongo#34]
Currently, if the DB update returns 'nupdated:0', the UI still says "Success!"

**Comment by mrvautin** [comment]
Are you able to give more info on this? A check is done on the returned nModified value and likely cause is displayed in a message?

**Comment by MaitreyaBuddha** [comment]
I noticed this when I couldn't edit my documents due to their _id being a number (https://github.com/mrvautin/adminMongo/pull/33). When the _id was casted to ObjectID type, it could not save the update and I saw 'nupdated:0' in my mongo logs. The UI, however, still said success. I haven't gotten back to dig more deeply, since this is just superficial and I fixed the underlying issue.

**Comment by MaitreyaBuddha** [comment]
My mongo/driver is returning 'n' instead of 'nModified'.
```
mongod --version
db version v2.4.12
```

Is that something that changed over versions? If so, I have a fix ready for a PR.

**Comment by mrvautin** [comment]
Mine returns the same an object like this:

`{ ok: 1, nModified: 1, n: 1 }`

It seems like MongoJS is returning the MongoDB result as per here: https://docs.mongodb.org/manual/reference/command/update/#update-command-output

Where `n` is the number of documents selected to be updated and `nModified` is the number of documents actually updated.

**Comment by MaitreyaBuddha** [comment]
That doc is for mongodb 3.2. With an unsuccessful edit, my return is `{ ok: 1, n: 0, upserted: [] }`. A successful one returns `{ ok: 1, n: 1 }`. There's isn't a corresponding page for my older version, but I can just check if `nModified` exists and use `n` if not.

**Comment by mrvautin** [comment]
Yeah I couldn't find any older docs either.

Out of interest, how are you simulating the failed update?

**Comment by MaitreyaBuddha** [comment]
I have a DB with numbers for _id. Without https://github.com/mrvautin/adminMongo/pull/33, editing fails.
