### ISSUE TITLE
Completely flattens the output

### ISSUE THREAD

**Issue by Happy-Ferret** [mrvautin/adminMongo#4]
I just gave adminMongo a try for the first time. 

Unfortunately, it completely flattened the document I was editing, beyond recognisability

The following is an excerpt from the document, the way it looked before editing it inside adminMongo.

```json
{
"description": {
    "cdata": "This is a proper description"
}
```

After pressing "Save document", adminMongo turned it into the following garbled mess. 

```json
{
"description[cdata]": "This is not a proper description",
}
```

The same is true for the whole document. Everything that wasn't a basic field (arrays, embedded documents, et al) got flattened into one.

**Comment by mrvautin** [comment]
Fixed in 6bcb2292d5ba241fe8a0ad2fbd51ef19bce82303.
