### ISSUE TITLE
Start adminMongo with context path

### ISSUE THREAD

**Issue by DCaldair** [mrvautin/adminMongo#40]
At the moment it's not possible to start adminMongo with a context path (e.g. 'http://localhsot:1234/<mongodb-ui>').

Is there any way to configure a context path?

**Comment by mrvautin** [comment]
I'm not really sure what you are wanting here? Can you explain further?

**Comment by DCaldair** [comment]
Sorry, my example is wrong.

I'd like to configure adminMongo to run with a context path like "http://localhost:1234/**adminMongo**/".

At the moment, when I start your app, it's alsway on the root path.

**Comment by mrvautin** [comment]
Ok I understand. I think though that adding the /adminMongo directive would be the job for a web server like Apache or Nginx and not the application.

**Comment by DCaldair** [comment]
I understand that.

We need to run adminMongo in a docker container. We habe some applications in docker container running and a proxy before them. We need all docker not to run in the root context. Most of them running a tomcat, so there is no problem. 

My hope was not to install a web server in the docker container for adminMongo.

**Comment by mrvautin** [comment]
There is no built in way to achieve this in Express. It's not impossible but I feel it would be best to leave it to the web server. I understand this doesn't help in your case but I would think (I could stand corrected) that the need for this would be pretty low with the majority of users.
