### ISSUE TITLE
After a document has been edited through adminMongo, my app was not able to find it anymore.

### ISSUE THREAD

**Issue by igordeoliveirasa** [mrvautin/adminMongo#41]
I edited a document and saved. It stays there, exactly right when I see through adminMongo. However, mongoose is not able to find it anymore. Whenever I edit a document, mongoose stops finding it.
What could it be? 

Thanks

**Comment by mrvautin** [comment]
`adminMongo ` uses `Mongojs `mainly to connect. Are you using `Mongoose` in your own app? If so, it's likely an issue with your own app, not `adminMongo`.

**Comment by igordeoliveirasa** [comment]
mrvautin, it looks like when it's edited/saved through admin mongo, it changes something on the document structure that my app is not able to list anymore. How can it be a problem at app if before editing at adminMongo it was able to list, and after editing ad adminMongo not anymore?

**Comment by igordeoliveirasa** [comment]
I've just downloaded another mongodb client (I'd indeed rather adminMongo), however, on the new mongodb client, after editing document, everything keep working. There is something on adminMongo corrupting some indexes or something like that..

**Comment by igordeoliveirasa** [comment]
I've just found out!!

Check it:

My original document is: 
{
name: string,
company: reference / foreign key
}

after edited through adminMongo it changed to:
{
name: string,
company: string
}

There is a problem at adminMongo editing.

**Comment by mrvautin** [comment]
This is related to issue #31. You will need to set an object ID using extended JSON formatting. Eg:
` { "$oid": "<id>" }`
 
Full documentation can be found here: https://docs.mongodb.org/manual/reference/mongodb-extended-json/

**Comment by igordeoliveirasa** [comment]
mrvautin, it shouldn't be user's responsibility. Since adminMongo detects that field as ObjectID, on edit mode it should be pre-configured as: "myAttributeId" : { "$oid": "<id>" } to be edited, not like: "myAttributeId" : "string" ...
Dont you think?

**Comment by mrvautin** [comment]
I agree. This is why I linked it to the other issue. Once that is fixed, this issue will also be fixed.
