### ISSUE TITLE
Listen on Localhost

### ISSUE THREAD

**Issue by sagargulati** [mrvautin/adminMongo#42]
Greetings,
I am using a dedicated server, even after updating app.json with server ip and a valid open port.
It can be only accessable via localhost using the IP and not from browsers.
Please help!

Thanks!

**Comment by mrvautin** [comment]
What would you like it accessible from? A DNS? 

If so, you would need to setup a web server like Nginx to proxy the requests.

**Comment by sagargulati** [comment]
I am running apache2 listening on port 80.
I can use that right?
Yes i want to access it from my public IP address of my apache web server.

**Comment by sagargulati** [comment]
@mrvautin : can u help please?

**Comment by mrvautin** [comment]
This is a sever config issue. You would need to follow a guide like: https://www.digitalocean.com/community/questions/how-to-run-nodejs-with-apache-for-ubuntu-12-04
