### ISSUE TITLE
Composite keys are not working

### ISSUE THREAD

**Issue by smil2k** [mrvautin/adminMongo#43]
In case your documents have composite keys, they don't work for "edit" and "delete".

**Comment by mrvautin** [comment]
Can you provide an example?

**Comment by smil2k** [comment]
Hi,

Example document:
{
  "_id": {
    "topic": "events",
    "partition": 0,
    "clientId": "secevents"
  },
  "offsetValue": 14
}

Link created for Edit button:
http://mongo-manager/Mongo-X/technical/offset/edit/%5Bobject%20Object%5D?type=object

Observe the "[object Object]" in the path. Most probably this is the source of the problem.

Cheers,

Tamas

**Comment by mrvautin** [comment]
Thank for reporting. At this stage it is difficult to support documents indexed like this. Maybe in the future something can be worked out.

I'm happy to accept a pull request if you fix it.
