### ISSUE TITLE
ENOENT, open '/views/layouts/layout.hbs' with Forever

### ISSUE THREAD

**Issue by remithomas** [mrvautin/adminMongo#46]
I got this error (not critical).

> Error: ENOENT, open '/views/layouts/layout.hbs'

This error appears when I start nodejs with _forever_ like this
`forever start /var/www/adminMongo/app.js`

But not with
`forever start app.js`

How to fix it ? Because it's very useful to manage my nodejs apps when I see all the paths with _forever list_
thanks

**Comment by mrvautin** [comment]
This is a `forever` related issue.

With `forever` you need to either start the app whilst residing in the directory of `adminMongo` or specify the `--sourceDir` value of the `adminMongo` install path (where the app.js file resides).
