### ISSUE TITLE
Global install doesn't move config

### ISSUE THREAD

**Issue by khaosdoctor** [mrvautin/adminMongo#47]
When performing an `npm i -g`, npm doesn't install the "config" folder in the node modules, this causes an error when adding connections ("file not found error") then you have to move the config folder manually.

**Comment by mrvautin** [comment]
Its likely because NPM hasnt been updated. I will check it out.

**Comment by khaosdoctor** [comment]
Maybe, because I've also noticed that when I did a simple `npm i -g admin-mongo` it installed an older version of the package, different from the repo.
