### ISSUE TITLE
Can't delete or edit documents

### ISSUE THREAD

**Issue by mrisinger** [mrvautin/adminMongo#5]
When I click the 'Delete' button next to a document and then click 'Yes' to confirm, the server dies with this error:
    
    /home/iast/repos/adminMongo/node_modules/mongodb/lib/mongo_client.js:465
          throw err
                ^
    Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
    at new ObjectID (/home/iast/repos/adminMongo/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/objectid.js:38:11)
    at ObjectID (/home/iast/repos/adminMongo/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/objectid.js:29:42)
    at /home/iast/repos/adminMongo/routes/index.js:740:62
    at /home/iast/repos/adminMongo/node_modules/mongodb/lib/mongo_client.js:462:11
    at process._tickCallback (node.js:355:11)
    
Also, when I click the 'Edit' button next to a document, the server doesn't log any errors, but the UI shows a big red error message that says 'Error - Invalid document ID length'

Let me know what kind of info would be helpful in debugging.  Thanks, this is a great project!

**Comment by mrvautin** [comment]
Both issues seem related. How long is the '_id' value? The '_id' is being cast to an ObjectID for updates/edits and queries. If this value is not 12 bytes or 24 hex characters there will be issues with the current code.

It's not common to use custom length "_id" values. Are you setting the "_id" value yourself or letting MongoDB do it?

**Comment by mrisinger** [comment]
The application uses _id values other than 12 byte values (some strings, some longer byte values).  I'm not in a position to change this implementation.  Would you consider this out of the scope for this project?

**Comment by mrvautin** [comment]
I don't think it is out of scope. I'm happy to remove the validation on 12 bytes of data as it is not needed. I'm finding it hard to replicate/fix the query to ensure adminMongo is not trying to find the document based on an ObjectID when your ID's are not MongoDB ObjectID's. Do you want to have a look at it for your setup? Here is where it will fail when not using ObjectID's for example: https://github.com/mrvautin/adminMongo/blob/master/routes/index.js#L339

**Comment by mrvautin** [comment]
This should be fixed in fdd4dd216f0fc709f547a86883f0dca9518eb834, sorry about the commit message not mentioning it at all.. ;)

If further issues or a better way of doing it, please comment on issue.

**Comment by mrisinger** [comment]
Thanks!
