### ISSUE TITLE
Installation failing in Ubuntu 12.02

### ISSUE THREAD

**Issue by gsusI** [mrvautin/adminMongo#51]
> npm install
npm http GET https://registry.npmjs.org/ace-builds
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/body-parser
npm http GET https://registry.npmjs.org/bootstrap
npm http GET https://registry.npmjs.org/config
npm http GET https://registry.npmjs.org/cookie-parser
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/express-handlebars
npm http GET https://registry.npmjs.org/font-awesome
npm http GET https://registry.npmjs.org/hbs
npm http GET https://registry.npmjs.org/jquery
npm http GET https://registry.npmjs.org/mongo-uri
npm http GET https://registry.npmjs.org/mongodb
npm http GET https://registry.npmjs.org/mongodb-extended-json
npm http GET https://registry.npmjs.org/mongojs
npm http GET https://registry.npmjs.org/morgan
npm http GET https://registry.npmjs.org/nconf
npm http GET https://registry.npmjs.org/serve-favicon

npm ERR! Error: failed to fetch from registry: bootstrap
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /root/adminMongo/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.2.0-93-virtual
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /root/adminMongo
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: bootstrap
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/adminMongo/npm-debug.log
npm not ok

**Comment by mrvautin** [comment]
This was caused by an old version of Nodejs. Updating to Ubuntu's latest fixed the issue.
