### ISSUE TITLE
Authentication Failed for Mongo DB 3.0

### ISSUE THREAD

**Issue by gopi8887** [mrvautin/adminMongo#54]
Hi,

When I am trying to connect to remote mongodb instance, I am getting Authorization Failed even through I entered correct credentials. Looks like this is because of ScramSHA1 auth Mechanism in Mongo 3.04. Does this app support it.

**Comment by mrvautin** [comment]
This app uses Mongojs which is a wrapper for the native driver.

Can you confirm you able able to connect with the native driver?

**Comment by gopi8887** [comment]
Hi Mark,

I am really not sure what the issue is. But after I repaired the mongo instance using Linux terminal and restarted the server, I was able to connect without any issues. I will add comment if I find any more details
