### ISSUE TITLE
Not able to start 

### ISSUE THREAD

**Issue by jeetmp3** [mrvautin/adminMongo#56]
I've clone the project and installed depenencies. When i am trying to run `npm start` it gives me below error
`npm start`
`>admin-mongo@0.0.3 start /mongo/adminMongo` 
`>node app.js`

`npm ERR! weird error 1`
`npm WARN This failure might be due to the use of legacy binary "node"`
`npm WARN For further explanations, please read`
`/usr/share/doc/nodejs/README.Debian`
 
`npm ERR! not ok code 0`

**Comment by mrvautin** [comment]
What version of NodeJs are you running? It's highly likely it's quite old and needs updating to the latest.

**Comment by jeetmp3** [comment]
Hi @mrvautin thanks for the quick response. My node link wasn't pointing to nodejs. Its working fine now :)
