### ISSUE TITLE
Modify default num of docs in collection list?

### ISSUE THREAD

**Issue by lukewendling** [mrvautin/adminMongo#57]
Is it possible to show more than 5 docs in a collection list, per page?

**Comment by mrvautin** [comment]
More than 5 per pagination page? No this is not a feature/setting currently.

**Comment by lukewendling** [comment]
@mrvautin yes. i'm touching up views and server routes to hack in a larger number. showing 25 or so is a somewhat common default value in other admin UIs, IMO, but of course not a critical thing. Thanks.

**Comment by mrvautin** [comment]
Fixed in 130b8582246a7aa1bd9a9dd1871c3c3ca66038e4. Added ability to override the default 5 docs per page by using the `/config/app.json` file.

**Comment by lukewendling** [comment]
:+1:
