### ISSUE TITLE
Ajax support ?

### ISSUE THREAD

**Issue by SkyzohKey** [mrvautin/adminMongo#59]
Hey guys,

First I want to thanks you for this usefull project!
I was deleting documents from my collection and saw that each deletion required a page refresh.
It would be nice if AJAX, or even better, [Fetch](https://github.github.io/fetch) would been supported ;)

**Comment by joeltmiller** [comment]
I'm willing to take a whack at this, expect a pull request soon.

Thoughts on using AngularJS? I'm not familiar with Fetch...

**Comment by mrvautin** [comment]
Sorry I've been busy lately. I would be happy to merge your PR.

It currently does an Ajax call but the notification refreshes the window to re-retrieve the pagination. This should be able to be fixed/changed pretty easily.

I looked and Angular but it seemed like a rewrite was too much work. If someone was to convert adminMongo to Angular, I would definitely merge it.

**Comment by joeltmiller** [comment]
Challenge accepted, I'll focus on this piece first and move towards porting everything to Angular.

Thoughts on Angular 1.x vs 2.x? I'd be apt to go with 1.x now being more stable...

Psyched! 😃

**Comment by mrvautin** [comment]
I agree. Angular 1.x seems like the best and most stable option _right now_. There are upgrade paths to move to Angular 2.x when it's more stable and production ready.

Let me know how you go.

**Comment by mrvautin** [comment]
Most API calls are "Ajax" and don't require page refresh. Closing this issue but happy to accept any PR's which improve this further.
