### ISSUE TITLE
CaseInsesitive Query or Using Regex

### ISSUE THREAD

**Issue by ajaysharavat** [mrvautin/adminMongo#61]
Hi,
How could I use regex in query documnents?

Regards

**Comment by mrvautin** [comment]
Regex is one of the only extended JSON which is not currently supported. It should be able to be added relatively easy I think. 

Do you have an example query you are trying to use I could test against?

**Comment by mrvautin** [comment]
Further to this, you can easily query use Regex EJSON. Eg:

To find documents with a building number starting with '15' you could use this JSON and the "Query Documents" button:

```
{"building" : { "$regex": "^15"}}
```

Again if you can provide a query you are trying to use, I or someone else can look at it further.

**Comment by thomasd3** [comment]
is it implemented now?
