### ISSUE TITLE
Production Use?

### ISSUE THREAD

**Issue by jmrezayi2** [mrvautin/adminMongo#63]
Hello,

First of all thanks a lot for this tool, it is great!
I have read the readme where it is stated:
"adminMongo connection information (including username/password) is stored unencrypted in a config file, it is not recommended to run this application on a production or public facing server without proper security considerations."

I was wondering if there is any plan on adding some sort of encryption; and/or authentication for someone who visits the UI.

Thanks!

**Comment by mrvautin** [comment]
What is your intention of use? `adminMongo` is a development/management tool and should not be installed on a public facing (production reference) server without locking it down using other means. It's safe to install on a local machine and use against a production MongoDB server if you wish.

It's possible to use `bcrypt` to store passwords but there isn't a big benefit.

**Comment by jmrezayi2** [comment]
Hello,

I understand. I was thinking of something like phpmyAdmin for mongoDB.

Anyways Thanks for the great tool!

**Comment by shahzadthathal** [comment]
I think there should be a login feature to access this tool.
