### ISSUE TITLE
Error when visiting localhost

### ISSUE THREAD

**Issue by ponchoa** [mrvautin/adminMongo#65]
Hello. First of all, thanks for making this GUI, it seems very useful. Unfortunately, I can't run it at the moment...

After cloning the repo, and installing the dependencies, I tried "npm start". (I am using Mingw64, on Windows 10 64 bits)
But when I tried accessing http://127.0.0.1:1234 in my browser, I had errors pop up in the shell:

> $ npm start

> admin-mongo@0.0.3 start C:\Users\Benoît\Documents\Projects\Mongo\adminMongo
> node app.js

> (node:10616) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
adminMongo listening on host: http://127.0.0.1:1234
C:\Users\Benoît\Documents\Projects\Mongo\adminMongo\node_modules\mongodb\lib\mongo_client.js:409
          throw err
          ^

> TypeError: Cannot read property 'indexOf' of undefined
    at module.exports (C:\Users\Benoît\Documents\Projects\Mongo\adminMongo\node_modules\parse-mongo-url\index.js:10:10)
    at new Database (C:\Users\Benoît\Documents\Projects\Mongo\adminMongo\node_modules\mongojs\lib\database.js:43:20)
    at module.exports (C:\Users\Benoît\Documents\Projects\Mongo\adminMongo\node_modules\mongojs\index.js:5:12)
    at C:\Users\Benoît\Documents\Projects\Mongo\adminMongo\routes\index.js:103:22
    at C:\Users\Benoît\Documents\Projects\Mongo\adminMongo\node_modules\mongodb\lib\mongo_client.js:406:11
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

> npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! admin-mongo@0.0.3 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the admin-mongo@0.0.3 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the admin-mongo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs admin-mongo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls admin-mongo
npm ERR! There is likely additional logging output above.

> npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Benoît\Documents\Projects\Mongo\adminMongo\npm-debug.log`

I tried tampering with the config file, adding the options:
`{
    "app": {
        "host": "127.0.0.1",
        "port": 1234,
        "docs_per_page": 15
    }
}`
to no avail. (I even tried setting a password. The prompt for the password worked, but as soon as it tried to connect, the same errors appeared.)

I included the npm-debug log:
[npm-debug.txt](https://github.com/mrvautin/adminMongo/files/283871/npm-debug.txt)

I hope I gave you all the information needed, if not, I will provide anything needed. Thanks again for the GUI, and for taking time reading this issue.

**Comment by Cyber1000** [comment]
I have the same problem on Ubuntu 14.04:
- going to http://127.0.0.1:1234/connection_list works
- but going to http://127.0.0.1:1234 results in the described bug (same log as above)
- I don't think it is a problem within adminMongo itself because I went some versions back (somewhere middle of march where I'm sure that it worked) and had the same problem.
- Had no time to investigate this further, please help.

**Comment by storrdev** [comment]
I'm experiencing the same error on OS X 10.11.4

**Comment by mqliutie** [comment]
I'm experiencing the same error on OS X 10.11.2 (15C50)

**Comment by mrvautin** [comment]
I'm finding it really hard to track down the cause of why it's stopped working all of a sudden as it relates to a dependant module. 

The issue relates to how `adminMongo` passes a native Mongodb object to the `mongojs` module. I will have to make a fix which moves from passing an object to passing a connection string as this seems to work better.

**Comment by mqliutie** [comment]
@mrvautin It's ok now

**Comment by mrvautin** [comment]
Thanks for letting me know @mqliutie. There is a fair few code changes, please let me know if I missed something and created issues. There aren't any tests for `adminMongo` (which I really need to get onto) so big changes are hard to test thoroughly.

**Comment by mqliutie** [comment]
@mrvautin  
I'm using it and it seems very well. 

If it has problems I will tell you
