### ISSUE TITLE
Connection end issue

### ISSUE THREAD

**Issue by allevo** [mrvautin/adminMongo#70]
Hi,
  in almost every route, there's instanced a new connection to mongo.
For example https://github.com/mrvautin/adminMongo/blob/master/routes/index.js#L100
But after use it, the connection is still alive after the http request ended.
It's better to create a pool of connections before the http sever starts and for each http request, get the connection from the pool and release after.

Both mongodb and mongojs libraries require that the connections should be closed.

**Comment by mrvautin** [comment]
Yeah fair call. I was never happy with it and it's something I needed to look at but didn't have time. 

I will leave this issue open.

**Comment by allevo** [comment]
I'm working on...

**Comment by mrvautin** [comment]
I've actually done it all and am testing it.
