### ISSUE TITLE
Not able to start application persistantly

### ISSUE THREAD

**Issue by sgsshankar** [mrvautin/adminMongo#72]
node app.js will not be able to keep the application running persistently. Very difficult to use in production without using shell.

So PM2 is used to run the process as a service.

Pull request #71 for this feature

**Comment by mrvautin** [comment]
I'm not sure `adminMongo` should be just limiting to just PM2. I would rather leave agnostic where people can start the app using PM2, forever, supervisor, node-dev etc.

**Comment by sgsshankar** [comment]
Agreed.
We will keep it Agnostic.

**Comment by sgsshankar** [comment]
Issue closed.
