### ISSUE TITLE
Feature request - please add ability to configure a context/prefix

### ISSUE THREAD

**Issue by nneul** [mrvautin/adminMongo#73]
`   { "app" : { "context" : "/adminMongo" } }     `

Would tell it to run in context "/adminMongo" instead of "/", allowing me to put adminMongo behind a frontend proxy server that serves up other content. Right now, it assumes it's rooted at /, so immediately redirects to /connection-name instead of /adminMongo/connection-name

**Comment by mrvautin** [comment]
Is this related to issue #60? The last comment details setting up with Nginx.

**Comment by nneul** [comment]
Yes, equivalent issue, thank you. Though the nginx approach described is a bit of a hack compared to just supporting a context (though admittedly doesn't require you to do anything) - and is not supported by many other frontends. For example using oauth2_proxy in front of it to provide oauth based authentication.

**Comment by nneul** [comment]
(Dup of comment on #60 ) The issue is that you're not using directory relative links in the app - you're using root relative links. So if the app is served up from a subdirectory of the site, all the references are wrong.

It's not clear to me that the provided suggestion will work properly either since the references in the generated content don't have a server name on them, they are just "/connectionname" and you certainly can't do a replace on "/".

**Comment by mrvautin** [comment]
Ok. I was reading something similar.

I'm happy to accept a PR if you have time or I can look at it further in a few days.

**Comment by nneul** [comment]
Yeah, looking at it now. Plan is to add a 'context' setting, and pass it in to to  each of the res.render calls, at least that looks like the right approach.

**Comment by nneul** [comment]
Can you take a look here and suggest anything for the question in it's description?

https://github.com/mrvautin/adminMongo/pull/74

**Comment by mrvautin** [comment]
Hmm ok. That seems a lot harder than what I was reading. I was under the impression from a quick read that we can add this to the `apps.js` file (if a context is set in config):

``` javascript
app.use('/chosen_context', router);
```

I could be wrong and might need to read further on this.

**Comment by nneul** [comment]
The issue is that will let you serve up the app itself as being located in that subdir. 

i.e. changing your app from responding to "/dbname" to "/context/dbname".

But, it will not change what html/links/etc. your app generates which are still going to be "/dbname".

**Comment by mrvautin** [comment]
Ok. It still might be cleaner than changing all the `res.render` plus adding `{{context}}` to all views links.

I might have to have a further look.

**Comment by nneul** [comment]
Very possibly... What's in the pull request now has the start of what I think it would need, but the javascript isn't seeing the variable/value - likely I'm missing something about how vars work in js/scope/etc.

**Comment by mrvautin** [comment]
Added this functionality in ca3d0534e2bc0d60975c199c5e3e0e4774a79ca6.

**Comment by JayceCao** [comment]
I deployed adminmongo with docker, the command is `docker run -d --name mongo-ui -e PORT=10001 -e CONTEXT=mongo -e MONITORING=true -p 127.0.0.1:10001:10001 --network mongo mrvautin/adminmongo`.  
The nginx configuration is:
```
location /mongo/ {
    proxy_set_header            Upgrade $http_upgrade;
    proxy_http_version          1.1;
    proxy_set_header            Connection 'upgrade';
    proxy_cache_bypass          $http_upgrade;
    proxy_set_header            Host $host;
    proxy_pass                  http://127.0.0.1:10001/mongo;
}
```

When opening web page with url `https://mysite.com/mongo/`,responses of all requests, including html request, css and js file requests, are all `404`.
