### ISSUE TITLE
Display of queried result

### ISSUE THREAD

**Issue by sarkar1** [mrvautin/adminMongo#79]
Hi, 
I am a newbie here trying out MongoDB for the first time. I just started using adminMongo. Great job you guys!
I had a very simple question. When we query a document, where should I expect to see the result? eg. 
```
db.mycol.find({"likes":{$gt:1000}})
```
Thanks!

**Comment by mrvautin** [comment]
If you are using the "Query documents" button you should be able to enter your query in the modal like:

```
{"likes":{$gt:1000}}
```

**Comment by sarkar1** [comment]
Thanks for the reply @mrvautin. I have tried the above format as well. It displays all my documents. ``` {"likes":1000} ``` displays 1 document. Operations like gt,lt,ne doesn't seem to work

**Comment by mrvautin** [comment]
Ok. I'm not sure that has been tested thoroughly. Let me have a look into it.

**Comment by mrvautin** [comment]
It seems the `mongodb-extended-json` module is struggling with parsing the query.

Can you try like this (note the quotes around "$gt"):

```
{"likes":{"$gt":1000}}
```

**Comment by sarkar1** [comment]
Now it works. Thanks!

**Comment by mrvautin** [comment]
Great!
