### ISSUE TITLE
Some collections are not shown/populated.

### ISSUE THREAD

**Issue by drakoumel** [mrvautin/adminMongo#8]
I have the following collections (data grabbed using mongo shell)

show collections
dashboards
datas
datasources
main
roles
users
widgets

now on the UI I cannot see 'datas' and 'users' always return empty.

If I force the url (datas/view?page=1) to navigate to my collection it returns the correct data. But that is not the case with users. Users is always empty.

to sum up. 1 collection is not shown on the list but if navigated to it lists everything. Users collection is shown but no documents

**Comment by mrvautin** [comment]
Is anything logged in the console when you browse to those collections?

**Comment by mrvautin** [comment]
This has fixed an issue where some collections were not showing in the sidebar list: 2d316c095f0877ee5d02fa6d52cacdcfbdaad562.

The URL structure you are using in your comment has changed slightly with the introduction of the search functionality. Can you pull the latest version of adminMongo and re-test to confirm its not resolved?

**Comment by drakoumel** [comment]
Both issues are now fixed Thank you great job!
