### ISSUE TITLE
Editing document with value 'null' in key:value pair

### ISSUE THREAD

**Issue by anriKogan** [mrvautin/adminMongo#83]
Hey guys,
I really like your cool and useful project, thank you for great work.
Recently I noticed when I add the new document into collection, and this document contains  key:value pair with 'null' value, I don't have editing this document any more I press 'edit' button and in the application log I see this exception:

/opt/adminMongo/node_modules/mongodb/lib/utils.js:98
    process.nextTick(function() { throw err; });
                                        ^
TypeError: Cannot call method 'toString' of null
    at /opt/adminMongo/routes/index.js:756:26
    at /opt/adminMongo/node_modules/lodash/lodash.js:4411:15
    at baseForOwn (/opt/adminMongo/node_modules/lodash/lodash.js:2654:24)
    at Function.forOwn (/opt/adminMongo/node_modules/lodash/lodash.js:12327:24)
    at /opt/adminMongo/routes/index.js:755:15
    at /opt/adminMongo/routes/index.js:1230:29
    at handleCallback (/opt/adminMongo/node_modules/mongodb/lib/utils.js:96:12)
    at /opt/adminMongo/node_modules/mongodb/lib/collection.js:1357:5
    at handleCallback (/opt/adminMongo/node_modules/mongodb/lib/utils.js:96:12)
    at /opt/adminMongo/node_modules/mongodb/lib/cursor.js:661:5

I will fix it by myself but I'm not familiar a lot with NodeJS and JavaScript.

**Comment by mrvautin** [comment]
Easy fix. This is new functionality, thanks for reporting it @anriKogan.

**Comment by anriKogan** [comment]
Well done!!! Thanks
