### ISSUE TITLE
'payload too large' error when adding 262kb json document

### ISSUE THREAD

**Issue by faxedhead** [mrvautin/adminMongo#9]
this is printed in the console in chrome: 

http://127.0.0.1:1234/my/myDB/person/insert_doc Failed to load resource: the server responded with a status of 413 (Payload Too Large)

not sure if it's the same bug, but when i press the 'edit' button on a json document of the same size in this collection, i get 'Error - Document not found' and a link to 'take me home', although nothing is printed in the console.

**Comment by mrvautin** [comment]
This is an issue with Express bodyparser defaulting to 100kb. I will make a change to up the limit to a few megabytes.

**Comment by faxedhead** [comment]
OK, Mongodb document size limit is 16Mb currently [according to the doco](https://docs.mongodb.org/manual/reference/limits/).

**Comment by mrvautin** [comment]
Fixed in 6932ead0d6e799d1bc18082b9e7ce26569401ba7. I set the value to 16MB. As you say the largest BSON document size is 16mb but I'm reading that BSON documents are generally larger than raw JSON due to additional metadata. The limit should cover off 99.99% of instances.
